---
- name: k8s uncordon
  hosts: all
  vars:
    mynode: "k8s.ansiblepilot.com"
  tasks:
    - name: uncordon node
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ mynode }}"
