---
- name: k8s memory
  hosts: all
  vars:
    myproject: "mem-example"
  tasks:
    - name: namespace present
      kubernetes.core.k8s:
        kind: Namespace
        name: "{{ myproject }}"
        state: present
        api_version: v1
    - name: memory pod
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: memory-demo
            namespace: "{{ myproject }}"
          spec:
            containers:
              - name: memory-demo-pod
                image: polinux/stress
                resources:
                  requests:
                    memory: "100Mi"
                  limits:
                    memory: "200Mi"
                command: ["stress"]
                args: ["--vm", "1", "--vm-bytes", "500M", "--vm-hang", "1"]
