---
- name: Listen for webhook events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 8000
  rules:
    - name: webhook
      condition: event.payload.message != ""
      action:
        run_playbook:
          name: playbook.yml
