---
- name: k8s scale
  hosts: all
  vars:
    myproject: "ansible-examples"
    mydeployment: "nginx"
    curr_replica: 10
    myreplica: 5
  tasks:
    - name: scale down
      kubernetes.core.k8s_scale:
        api_version: v1
        kind: Deployment
        name: "{{ mydeployment }}"
        namespace: "{{ myproject }}"
        current_replicas: "{{ curr_replica }}"
        replicas: "{{ myreplica }}"
