---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: ansible-examples
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
    - name: nginx
      image: nginx:1.21.6
      ports:
        - containerPort: 80
          name: http-web-svc
