---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ansible-examples
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
    - name: service-port
      protocol: TCP
      port: 80
      targetPort: http-web-svc
